### ISSUE TITLE
genSha1对超大文件的处理会导致内存被耗尽

### ISSUE THREAD

**Issue by xbee** [Rogerzhao/dirscan_tool#2]
这里没有对缓冲区的大小进行限定，将会导致内存被耗尽

```
buf, err := ioutil.ReadFile(f.fileName)  
```

**Comment by Rogerzhao** [comment]
func (f *FileInfo) genSha1() (err error) {
    buf := make([]byte,1024)
    file, err := os.Open(f.fileName)
    if err != nil {
        xmlog.ERROR(err)
        return
    }
    defer file.Close()
    fileReader := bufio.NewReader(file)
    h := sha1.New()
    for {
        n, err1 := fileReader.Read(buf)
        if err1 == io.EOF {
        if n > 0 {
            io.WriteString(h,string(buf[:n]))
        }
        break
        }
        if err1 != nil {
        err = err1
        xmlog.ERROR(err)
        return
        }
        io.WriteString(h,string(buf[:n]))
    }

```
f.sha1 = fmt.Sprintf("%x", h.Sum(nil))
output := fmt.Sprintf("%s,%s,%d", f.fileName, f.sha1, f.size)
outputChan <- output
syncChan <- 1

concurrentChan <- 1
return
```

}

Through read the buf in a loop, large scale file problem solved. Thanks, What is more, I ge to know that no need to read the whole file content to calculate its sha1.
